//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurgerPlus.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id { get; set; }
        public int idCustomers { get; set; }
        public int idProduct { get; set; }
        public int Count { get; set; }
        public string tip { get; set; }
        public int price { get; set; }
        public int total { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Product Product { get; set; }
    }
}
