//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurgerPlus.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production
    {
        public int id { get; set; }
        public int IdProduct { get; set; }
        public int CountProduct { get; set; }
        public string tipProduct { get; set; }
        public int IdMaterial { get; set; }
        public int CountMaterial { get; set; }
        public string tipMaterial { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Product Product { get; set; }
    }
}
