//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurgerPlus.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public int IdRole { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<int> failed_attempts { get; set; }
        public Nullable<bool> is_locket { get; set; }
        public Nullable<System.DateTime> lockout_expires { get; set; }
    }
}
